{% set version = "1.8-2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-spatstat.utils
  version: {{ version|replace("-", "_") }}

source:
  fn: spatstat.utils_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/spatstat.utils_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/spatstat.utils/spatstat.utils_{{ version }}.tar.gz
  sha256: 577811295b7269a20d0d72763639dd29e3226d86fbf03e2a230e41ec21e45bf2

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix  # [win]
    - {{native}}toolchain  # [win]
    - gcc  # [not win]
  run:
    - r-base
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('spatstat.utils')"  # [not win]
    - "\"%R%\" -e \"library('spatstat.utils')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/spatstat.utils
  license: GPL (>= 2)
  summary: Contains utility functions for the 'spatstat' package which may also be useful for
    other purposes.

extra:
  recipe-maintainers:
    - ocefpaf
