travis:
  secure:
    BINSTAR_TOKEN: WMGQ07tpwlNVe+F9TaMFFXdDJLRfLDG+xU4Unii3tLSfRjTzA6SglUDmYC4eaVtAD82vjijAejOBTnqGyqn3p7zdIub5cTRFk7ovii5qASCt2UjKYI+wNNywRvtFetM4sI/BUNCIO5qdqCeTc9C2ySCNqMout/jcK4B2bdcLnfe39JqS9IEQ5fMVWmxJ1vLL8TO0iOEuM3619X7fRcjmPH8PHy/80pRtIuR9qn1JtNZkGcsR1y1n74E8PVOE0C0RHaIO/kEdGYR5mrulzB6pDfdDiSHuhRsZ157k90xm2d13X6W+JT+snEegHE75lWKwvFMH+A94WdqmXwYkpqxG+QznCkGe+WBtOO/G9inCm6fnyyv6L8lhrxMhyxBuFYbsrV//J1YY67qXIAlCQvJmhA0Ektxq38fv4EZcuTxmTBE/fbI5ZSSnEgn2zvxw7lsfYwvJ5prj4MVIfXmWjIkPEzBGumoVaiEbO6+5fST+RKnhyDgJmCrU0tWpBfvXAVgIV4IdzjXGOVE8e8MtqH5sbznzbwdk1ng3CW/om7IroXoLHUT29GwKZGYtz9Oce4GHu2SVv79JOw5K8abjyl96lYKur1+3rI3I74jm2EUH4SLsk9VLBPzWzzJf6hNlRgPXvhkilzlJQ7cCoaVeG6r9q6e7NF7ispcSvsn+qAnN2R0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
