appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: n8dJUvDl76mO8UXDogMxbelVlyYNLhjX2Io1ic9kFiY9nqJqPwx07qrr5kzjZboaW8cSxmtUKYVPROkI6zI0VouJT9mJrE0NrD1ab3OwVFUyZtJZGA7Ca5oxSNWqKjSTvM9ThMXl24mwkUIuc83kSDlHidB+t9io5MexV1g7G/HbyFaEX3WCjUhz4ju1vkqQ99lBxU/QgIOgYNdFdk6FH2VCafydAJIJk7UTkghEltWbHKdJo+hm4K1YZNcJypazoRy66FJp36RbPw+ETR5bfCkW0FH/q/npYjqo3GA18pBWYC9K+dIVz++zum5Pqn19o3yTCKma8TB+VEGFvOJvp656GPXauTF5J3xqpsPVcg8CCQFUrkznWJQdmonE/uMcQC7Pgs4C5ljJ1QkDS0CXNCmPjvS9eZzhxUJBcG9eFWwVOryeLE/UoRZeSstUalp+1DCRnGUDfYZhcpO6iL7x/DC5TgNcHWR6pGAp8M6cPSvNVRll122PudBmAgbQUuFiqk3bnqM3cFbrZFSj4f3+a3u35nGgmyOqZmKwTsDQkJkUHZmEJl8xK9ezOf3lIgis+NV5GjdM3oH8T9fiOoJCyhZkPIVtTvrqc/GF2h60Yb1Jb0hXfRvKoq7eWZvqGSIY/vXklikVB4p+MrClqueUkzvbg85JcbjNBg4h3jM0rHo=
conda_forge_output_validation: true
